export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_CATEGORYS = 'receive_categorys'
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_USERINFO = 'receive_userinfo'
export const RESET_USERINFO = 'reset_userinfo'
export const RECEIVE_SHOPGOODS = 'receive_shopgoods'
export const RECEIVE_SHOPRATINGS = 'receive_shopratings'
export const RECEIVE_SHOPINFO = 'receive_shopinfo'
export const INCREMENT_FOOD_COUNT = 'increment_food_count'
export const DECREMENT_FOOD_COUNT = 'decrement_food_count'
export const CLEAR_FOOD_CONT = 'clear_food_cont'

export const RECEIVE_SEARCH_SHOPS = 'receive_search_shops'
